repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        language: python
-   repo: https://github.com/python/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: ['-l 120']